version: '3.9'

volumes:
  storage: {}

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./web:/home/web/web
    env_file:
      - ./.env
    depends_on:
      - database

  database:
    image: postgres:15.1-alpine3.17
    restart: always
    volumes:
      - storage:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sussurros
      POSTGRES_DB: sussurros
      POSTGRES_PASSWORD: sussurros
