# Generated by Django 4.1.5 on 2023-01-31 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-published",),
                "verbose_name": "article",
                "verbose_name_plural": "articles",
            },
        ),
        migrations.AddField(
            model_name="article",
            name="published",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="published"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(
                default=0,
                max_length=250,
                unique_for_date="published",
                verbose_name="slug",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["-published"], name="articles_ar_publish_84008d_idx"
            ),
        ),
    ]
